[package]
name = "xtask"
authors = ["sisungo <sisungo@icloud.com>"]
version = "0.1.0"
license = "MIT"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1"