[package]
name = "airlog-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
once_cell = "1"
tokio = { workspace = true }

[build-dependencies]
built = "0.7"